name: Build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install zig
      run: sudo snap install zig --classic --beta

    - name: Build
      run: |
        for target in \
          aarch64-linux-musl \
          aarch64-macos-none \
          x86_64-linux-musl \
          x86_64-macos-none
        do
          zig cc -target "$target" -Os -s -o secret-${target%-*} secret.c
          gzip -9 secret-${target%-*}
        done

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" secret-*.gz \
          --title "secret ${{ github.ref_name.replace('v', '') }}"
